version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app  # Mount source code for hot reload
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    restart: unless-stopped
